lib/determinator/control.rb, lib/determinator/feature.rb, lib/determinator/retrieve/routemaster.rb, spec/determinator/control_spec.rb
This PR
* adds a new instance variable `:winning_variant` for feature model
* returns the winning variant as a winner if its set
=> Honour the winning_variant

examples/determinator-rails/config/initializers/determinator.rb, lib/determinator/retrieve/null_cache.rb, lib/determinator/retrieve/routemaster.rb, spec/determinator/retrieve/routemaster_spec.rb
Optional `retrieval_cache` argument for `Determinator::Retrieve::Routemaster`.
Should ideally be a new `ActiveSupport::Cache::MemoryStore.new(expires_in: 1.minute)` - although anything that quacks like a ActiveSupport cache store will do
=> LT-726/allow an ActiveSupport::Cache::Store to be passed into the determinator 

CHANGELOG.md, lib/rspec/determinator.rb, spec/rspec/determinator_spec.rb
Having accidentally merged the work (!) this PR fleshes out the specs for the RSpec helpers for determination.
```ruby
require 'rspec/determinator'
RSpec.describe YourClass, :determinator_support do
context "when the actor is in variant_a" do
forced_determination(:experiment_name, 'variant_a')
it "should respond in a way that is defined by variant_a"
end
context "when the actor is not in the experiment" do
forced_determination(:experiment_name, false)
it "should respond in a way that is defined by being out of the experiment"
end
context "when the actor is not from France" do
forced_determination(:experiment_name, 'variant_b', only_for: { country: 'fr' })
it "should respond in a way that is defined by being out of the experiment"
end
end
```
=> FLO-14: Adds RSpec helper library for determination

CHANGELOG.md, lib/determinator/retrieve/routemaster.rb, spec/determinator/retrieve/routemaster_spec.rb
Allows Determinator to accept both old-style constraints and overrides (arrays of keys) and new style (hashes)
===
Jira story [#FLO-12](https://deliveroo.atlassian.net/browse/FLO-12) in project *Florence*:
> ## What
> 
> Determinator currently cannot understand Hash constraints or overrides. We need to move actor tracking to emit these at some point (FLO-3, FLO-1), but Determinator must be able to cope with these beforehand.
=> FLO-12: Hash Overrides and Constraints

CHANGELOG.md, lib/determinator/version.rb
Releases v0.9.0, a feature complete RC for v1.0.0 - only docs remain!
=> 🆙 Release v0.9.0

CHANGELOG.md, README.md, lib/determinator/actor_control.rb
Fixes an issue where PR #27 missed one instance of syntactic sugar where `constraints` needed to be switched to `properties`.
=> FLO-21: Fixes typo from PR #27

CHANGELOG.md, lib/determinator/control.rb, lib/determinator/retrieve/routemaster.rb, spec/determinator/control_spec.rb
Make sure all constraints and properties are string-keyed so they match when they are the same.
FLO-26
=> FLO-26: Make sure constraints and properties match

CHANGELOG.md, lib/rspec/determinator.rb, spec/determinator/retrieve/routemaster_spec.rb, spec/rspec/determinator_spec.rb
`Determinator.configure` is usually called in such a way that it is executed before specs are loaded, meaning that `RSpec::Determinator` is useless. This change stubs `Determinator.instance` instead, which brings back the required functionality.
FLO-28
=> 👨‍🔧 More usable RSpec::Determinator

CHANGELOG.md, README.md, lib/determinator.rb, lib/determinator/control.rb, lib/determinator/retrieve/routemaster.rb, spec/determinator/control_spec.rb
- Stops routemaster from shouting when there is a legitimate 404
- Allows implementers to track missing features in whatever way they like.
===
Jira story [#FLO-37](https://deliveroo.atlassian.net/browse/FLO-37) in project *Florence*:
> ## What
> 
> When a feature doesn't exist we shouldn't be raising an exception (as we can't always control what features are requested - eg. the `/config` endpoint).
> 
> We _should_ however track when a feature is missing.
=> FLO-37: Swallow not-found routemaster errors

CHANGELOG.md, README.md, docs/local_development.md, lib/rspec/determinator.rb, spec/rspec/determinator_spec.rb
Allows the use of example-scoped variables for outcomes and constraints in `RSpec::Determinator`'s mocks.
=> Support example-scoped variables in RSpec

CHANGELOG.md, lib/determinator.rb, lib/determinator/retrieve/routemaster.rb
Adds the `Determinator.feature_details` method, which allows lookup of feature details as are currently available to Determinator. Whatever is returned here is what Determinator is acting upon.
Adds a little extra YARDoc for the good times.
```irb
> Determinator.feature_details(:my_exciting_feature)
=> #<Determinator::Feature:0x007fdc7a3f9f48
@active=true,
@bucket_type=:guid,
@identifier="my_exciting_feature",
@name="my_exciting_feature",
@overrides={},
@target_groups=[<100.0% of those matching: #<Hashie::Mash>>],
@variants={},
@winning_variant=nil>
```
=> Add helper method for feature lookup

CHANGELOG.md, examples/determinator-rails/Gemfile.lock
The example rails app depended on nokogiri 1.7.1, which has a known vulnerability.
=> 👨‍⚕️ Fix vulnerable dependency in example

CHANGELOG.md, README.md, lib/rspec/determinator.rb, spec/rspec/determinator_spec.rb
The mocking classes didn't allow .for_actor, but now they do.
=> 👨‍🎨 Allow for_actor on fake determinator

CHANGELOG.md, README.md, lib/determinator.rb, lib/determinator/control.rb, spec/determinator_spec.rb
Gives a framework for running a callback when a determination is made. This allows for simple and centralised tracking of experiments:
```ruby
Determinator.on_determination do |id, guid, feature, determination|
if feature.experiment? && determination !== false
YourTrackingSolution.record_variant_viewing(
user_id: id,
experiment_name: feature.name,
variant: determination
)
end
end
```
=> 👀 Determination callbacks

CHANGELOG.md, README.md, lib/rspec/determinator.rb, spec/rspec/determinator_spec.rb
FLO-42: Reverse the order of forced determination priority (least surprise)
FLO-41: Ensure properties & only_for specifications are normalised
===
Jira story [#FLO-41](https://deliveroo.atlassian.net/browse/FLO-41) in project *Florence*
Jira story [#FLO-42](https://deliveroo.atlassian.net/browse/FLO-42) in project *Florence*
=> 💎 Improve forced determination

README.md
This commit fixes a small typo in the initializer config
name > feature_name
=> Fix typo in readme initializer config

docs/local_development.md, lib/determinator/retrieve/file.rb
At the moment it looks like it's a bit tricky to get fake florence set up in orderweb for local testing.
The setup looks like this:
```
if App.context.roobus.enabled && App.context.actor_tracking.enabled
retrieval = Determinator::Retrieve::Routemaster.new(
discovery_url: App.context.drain_cache.hosts.actor_tracking
)
else
retrieval = Determinator::Retrieve::NullRetriever.new(discovery_url: '')
end
```
That means you have to be able to boot routemaster.
This PR makes a small change to the File reader and proposes an easier setup without any external dependencies.
=> Copy for easier local dev setup

README.md, docs/background.md
We had a hard time figuring out where to find the server-side part of Determinator + Florence (i.e. where feature flags and experiments are stored). This small change in the docs would have saved us some time.
=> Mention actor-tracking in docs

lib/determinator/control.rb, spec/determinator/control_spec.rb
- Minimises user surprise by ensuring the 'use nothing' buckets result in randomness for 1-99% rollouts.
- Introduces non-deterministic tests and 99.999% probability (so the test can be black-box, but will be flakey roughly one in 100,000 executions)
FLO-49
=> Mid-rollout single buckets are random

README.md, lib/determinator.rb, lib/determinator/cache/fetch_wrapper.rb, lib/determinator/retrieve/http_retriever.rb, spec/determinator/cache/fetch_wrapper_spec.rb, spec/determinator/retrieve/http_retreiver_spec.rb, spec/spec_helper.rb, spec/support/retreiver_spec.rb
Since 2.0 removed the dependency on RoutemasterCaache it's no longer possible to do routemaster style cache invalidation. One of the migration paths out into kafka is to use this pattern.
This PR adds a HttpRetriever and a tiered caching solution that makes it easier to use determinatior with some sort of bus.
=> Add HttpRetriever and modify the cache to cascade

CHANGELOG.md, README.md, lib/determinator/control.rb
Prior to this change, Determinator didn't allow to do semver comparison on constraints. Without this it was hard to target a certain feature to a certain set of apps.
This change adds support for a new kind of constraint, app_version. An app_version constraint can be set this way:
app_version => [">=1.2.3", "<=1.3"]
The property passed to determinator would be with the following format:
app_version => ["1.2.4"]
=> Add support for app_version property

.gitignore, CHANGELOG.md, lib/determinator/control.rb, lib/determinator/retrieve/in_memory_retriever.rb, lib/rspec/determinator.rb, spec/rspec/determinator_spec.rb
Currently `RSpec::Determinator` uses a separate implementation of determination for features and variants that does not support the new `app_version` constraint property.
This PR changes `RSpec::Determinator` so that instead of using a stub determinator implementation it uses the real determinator and injects features using an in-memory feature repository that is cleared out between specs.
This can make testing some cases harder, but there's an advantage in that you'll find out if your feature constraints will actually work in your tests rather than when you go to configure them in staging for the first time.
This breaks some Orderweb specs - I have an [Orderweb PR](/deliveroo/orderweb/pull/14780) that addresses these breakages.
A worked example of the change - previously …
=> fake determinator support for app version

CHANGELOG.md, lib/determinator.rb, lib/determinator/cache/fetch_wrapper.rb, lib/determinator/control.rb, lib/determinator/error_response.rb, lib/determinator/missing_response.rb, lib/determinator/retrieve/dynaconf.rb, lib/determinator/retrieve/file.rb, lib/determinator/retrieve/http_retriever.rb, spec/determinator/cache/fetch_wrapper_spec.rb, spec/support/retreiver_spec.rb
In instances where a connection to the actor tracking server may be unreliable you wouldn't want to cache all 404s so this pr introduces a new setting to turn that off.
Also, this pr makes a distinction between errors and 404 when communicating with an upstream service either by http or dynaconf.
=> Introduce a setting allowing the user to control if 404s should be cached

README.md
The `only_for` argument has caused an engineer some confusion recently — this readme change may prevent similar confusions in the future.
=> Make `RSpec::Determinator` clearer

CHANGELOG.md, README.md, determinator.gemspec, lib/determinator.rb, lib/determinator/tracking.rb, lib/determinator/tracking/context.rb, lib/determinator/tracking/determination.rb, lib/determinator/tracking/rack/middleware.rb, lib/determinator/tracking/request.rb, lib/determinator/tracking/sidekiq/middleware.rb, lib/determinator/tracking/tracker.rb, spec/determinator/tracking/rack/middleware_spec.rb, spec/determinator/tracking/sidekiq/middleware_spec.rb, spec/determinator/tracking/tracker_spec.rb, spec/determinator/tracking_spec.rb, spec/determinator_spec.rb
This adds a Rack middleware that collects all the determinations made during a request; and provides a hook to report them, along with request metrics (time spent, response status, error).
This will enabled enhanced logging for debugging purposes, and allow us to correlate request metrics with specific flags / experiment conditions.
=> Add tracking middleware

CHANGELOG.md, lib/determinator/version.rb
substational functionality was introduced with determinator-tracking, hence the minor version bump (as I'd like people to read the release notes!)
=> bump version to 2.4.0

CHANGELOG.md, lib/determinator/retrieve/in_memory_retriever.rb, lib/determinator/retrieve/null_retriever.rb, lib/determinator/version.rb, spec/determinator/retrieve/null_retriever_spec.rb
- For tests we use `Determinator::Retrieve::InMemoryRetriever` to allow simple setting of features in test contexts
- `InMemoryRetriever` (and `NullRetriever`) both currently return `nil` rather than `MissingResponse`, the later being what the regular retrievers return
- This triggered an error in local development where code that was expecting a missing feature to be `nil` rather than `MissingResponse`
- `Determinator::Retrieve::InMemoryRetriever` returns a `MissingResponse` when a feature is not present
- `Determinator::Retrieve::NullRetriever` always returns a `MissingResponse`
=> return MissingResponse rather than nil to match standard behaviour

CHANGELOG.md, README.md, lib/determinator/tracking.rb, lib/determinator/tracking/rack/middleware.rb, lib/determinator/tracking/request.rb, lib/determinator/tracking/sidekiq/middleware.rb, lib/determinator/tracking/tracker.rb, spec/determinator/tracking/rack/middleware_spec.rb, spec/determinator/tracking/sidekiq/middleware_spec.rb, spec/determinator/tracking/tracker_spec.rb, spec/determinator/tracking_spec.rb
As an additional piece of information in the tracked requests, we add the `endpoint` - for Rack requests, if possible, Rails controller and action, or HTTP method and request path; for Sidekiq requests, the name of the job.
In addition, this changes `Determinator::Tracking::Request#start` to be the request start time (instead of the monotonic start time, which is platform-specific).
=> Add endpoint tracking

CHANGELOG.md, lib/determinator/tracking/rack/middleware.rb, lib/determinator/version.rb, spec/determinator/tracking/rack/middleware_spec.rb
Use `sinatra.route`, if present, for tracking endpoint.
Also, removes `PATH_INFO` / `REQUEST_URI`: since the objective of the endpoint is to be able to aggregate calls for the same code path, getting the full url is not useful, as it's likely to contain path parameters.
=> Add sinatra.route and remove path info

CHANGELOG.md, lib/determinator/tracking/determination.rb, lib/determinator/tracking/tracker.rb, lib/determinator/version.rb, spec/determinator/tracking/tracker_spec.rb
Some endpoints have a lot of repeated calls to the same determinations. This compacts the internal list by keeping track of the repetitions, instead of adding an item each time.
=> Count repeated determinations in tracker

CHANGELOG.md, lib/determinator/control.rb, lib/determinator/feature.rb, lib/determinator/serializers/json.rb, lib/determinator/version.rb, spec/determinator/feature_spec.rb, spec/determinator/retrieve/http_retreiver_spec.rb, spec/factories/features.rb
Adds `structured_path` to the Feature object, to be used for "context objects". And adds an optional `feature` argument to the determination methods. This allows the context object library to obtain information from the feature first, and then use the Control for determination, avoiding fetching the feature twice (and not relying on the retrieval cache to be present to avoid that).
=> Allow passing feature for determinations

CHANGELOG.md, lib/determinator/control.rb, lib/determinator/version.rb
If an app uses caching, it might still have `nil` for `fixed_determinations` when the gem is updated. This adds a check to ensure this doesn't cause an error.
=> Return early if fixed_determinations missing

CHANGELOG.md, lib/determinator/control.rb, lib/determinator/version.rb
Structured determinations pass in `request.app_version`, so the version logic should be applied to that as well.
=> Apply app_version logic to request.app_version

CHANGELOG.md, lib/determinator.rb, lib/determinator/version.rb, lib/rspec/determinator.rb, spec/rspec/determinator_spec.rb
Without a feature cache Determinator will make direct calls to actor tracking every time a feature that doesn't exist is referenced.
This requirement will break code which incorrectly doesn't have one configured.
=> XPT-1976: Feature cache no longer optional

determinator.gemspec, spec/determinator/cache/fetch_wrapper_spec.rb, spec/determinator/explainer_spec.rb, spec/determinator/feature_spec.rb, spec/determinator/tracking/tracker_spec.rb, spec/determinator/tracking_spec.rb, spec/determinator_spec.rb, spec/factories/features.rb, spec/factories/target_groups.rb, spec/spec_helper.rb
FactoryGirl renamed their gem to FactoryBot some time ago. I support this move, it's about time we changed the references in this library.
Also fixed some deprecation warnings from the v5 FactoryBot bump (which I'm sure we'll be doing soon).
=> Long overdue move to FactoryBot

.github/workflows/gem-push.yml
Oh no.
One more PR to ensure we have the git username/email that the tag push requires.
=> Ensure git username is added

CHANGELOG.md, lib/determinator/control.rb, lib/determinator/feature.rb, lib/determinator/version.rb
Adapts the library to the [standard tests change](https://github.com/deliveroo/determinator-standard-tests/pull/13) which now requires all constraints to be an array of strings, and for the library to return an error if they aren't.
=> Ensure constraints are arrays of strings

lib/determinator/control.rb, spec/determinator/control_spec.rb
When guid is not supplied for a guid bucketed feature, returns false instead of throwing an error.
https://deliveroo.atlassian.net/browse/PROM-1156
=> Returns false instead of throwing an error

CHANGELOG.md, lib/determinator/version.rb
Increases the gem version for the [implementation](https://github.com/deliveroo/determinator/pull/111) of `when no guid is supplied for a guid bucketed feature, returns false instead of throwing an error.`
https://deliveroo.atlassian.net/browse/PROM-1156
=> Increases the gem version to 2.8.0

CHANGELOG.md, lib/determinator/control.rb, lib/determinator/version.rb, spec/determinator/control_spec.rb
Ticket: https://deliveroo.atlassian.net/browse/RPE-691
Related spec updates: https://github.com/deliveroo/determinator-standard-tests/pull/15
The Determinator gem raises an exception on `app_version`s with the following format: 2021.11.05. It should just return false on that determination if the input is invalid.
According to the semantic versioning specs none of the components of the version number should have any trailing zeros. So the above version should be 2021.11.5.
Setting the above non-compliant app version caused the following issue:
Sentry: https://sentry.io/organizations/deliveroo/issues/2813035755/?project=1460916&query=is%3Aunresolved
=> RPE-691: Ignore app versions not compliant with semver specs

CHANGELOG.md, lib/determinator/feature.rb, lib/determinator/version.rb, spec/determinator/feature_spec.rb
Depending on the serializer generating the feature, the fixed determination variant might be an empty string. When that's the case, it should be considered as empty.
=> Ignore fixed determination variant if blank

CHANGELOG.md, lib/determinator/actor_control.rb, lib/determinator/cache/fetch_wrapper.rb, lib/determinator/version.rb
We are planning to use determinator cache wrapper from the multiple threads. Even though all the used cache stores are individually thread-safe, Determinator::Cache::FetchWrapper class isn't.
=> Add mutex to the cache wrapper

.github/workflows/gem-push.yml
Github action actions/setup-ruby@v1 is deprecated and is no longer maintained. Need to migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
Related to https://deliveroo.atlassian.net/browse/XPT-5164.
=> Upgrade github action setup for deployment

.github/CODEOWNERS
This PR has been raised by the Product Security Engineering team as no CODEOWNERS file was found in this repository. The benefit of the CODEOWNERS file is to be able to easily identify who owns this code and enables automatic peer reviewer assignment when a PR is raised.
---
Currently the CODEOWNERS is blank.
1. Please edit the file to add in the name of the codeowner(s)
2. Merge the PR
If this PR was raised by mistake and a CODEOWNERS file is not needed, feel free to close this PR.
---
Guidance on the syntax is included in the [github CODEOWNERS Documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
=> ci:add codeowners template
